<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SolarShade.PvBattery/SolarShade.PvBattery.csproj" />
    <ProjectReference Include="../../IrradianceDataExtractor/SolarShade.Irradiance/SolarShade.Irradiance.csproj" />
  </ItemGroup>
</Project>
